apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: morphflow

resources:
  - namespace.yaml
  - configmap-app.yaml
  - secret-app.yaml
  - postgres.yaml
  - redis.yaml
  - kafka.yaml
  - api.yaml
  - worker.yaml
  - hpa-api.yaml
  - hpa-worker.yaml
