apiVersion: 1

datasources:
  - name: Prometheus
    uid: morphflow-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090/prometheus
    isDefault: true
    editable: false
