apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: morphflow

resources:
  - prometheus.yaml
  - grafana.yaml
  - jaeger.yaml
  - exporters.yaml

configMapGenerator:
  - name: morphflow-prometheus-config
    files:
      - prometheus.yml=configs/prometheus.yml
  - name: morphflow-prometheus-rules
    files:
      - prometheus-rules.yml=configs/prometheus-rules.yml
  - name: morphflow-grafana-datasource
    files:
      - prometheus.yml=configs/grafana-datasource-prometheus.yml
  - name: morphflow-grafana-dashboard-provider
    files:
      - dashboards.yml=configs/grafana-dashboard-provider.yml
  - name: morphflow-grafana-dashboards
    files:
      - morphflow-overview.json=configs/morphflow-overview.json

generatorOptions:
  disableNameSuffixHash: true
