[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name              tail
    Tag               containers.*
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    DB                /tmp/flb_docker.db
    Mem_Buf_Limit     20MB
    Skip_Long_Lines   On
    Refresh_Interval  5

[FILTER]
    Name   modify
    Match  containers.*
    Add    service morphflow

[OUTPUT]
    Name          es
    Match         containers.*
    Host          elasticsearch
    Port          9200
    Logstash_Format On
    Logstash_Prefix morphflow
    Suppress_Type_Name On
    Replace_Dots On
    Retry_Limit   False
